### PR TITLE
Update NanaZipShellExtension.cpp

### PR DESCRIPTION
**Pull request by modz2014**
Addressing the NanaZip duplication issue has been resolved by eliminating its presence in the classic context menu, ensuring a streamlined and efficient user experience while maintaining its accessibility in the new context menu. https://github.com/M2Team/NanaZip/issues/328#issue-1864475870

### CODE REVIEW

**Comment by MouriNaruto** [comment]
First, thanks for your PR and I'm sorry because I've been busy with other projects in recent days.

I haven't merged your PR because I need some time to understand the modifications.

I think we can utilize this not only on Windows 11 or later. So, I need to have more time to think.

Kenji Mouri

**Comment by modz2014** [comment]
i can explain it to you soon I have also done a few other fixes and feature for people for you

**Comment by modz2014** [comment]
this code works by first checking if the user is running Windows 11 or later using the IsWindows11OrLater function. Based on the Windows version and certain conditions (selection and okToBeSlow), it determines whether the context menu item should be visible and enabled (ECS_ENABLED) or hidden (ECS_HIDDEN). This provides a way to customize the behaviour of the context menu item based on the Windows version and user interaction.

**Comment by MouriNaruto** [comment]
I am not making you explain the implementation.

I think maybe this feature can be used in all supported Windows versions. 

Also, we need to consider the third-party apps which use the context menu. (They also can use the okToBeSlow parameter to optimize the user experience.)

Kenji Mouri

**Comment by modz2014** [comment]
Thank you for your input, Kenji. You're absolutely right; expanding this feature to all supported Windows versions could be beneficial. It's essential to consider the broader ecosystem, including third-party apps that utilize the context menu. By allowing them to use the 'okToBeSlow' parameter, we can indeed optimize the user experience and ensure compatibility across various applications. Let's further explore this possibility and assess the potential impact on our development roadmap @MouriNaruto

**Comment by modz2014** [comment]
@MouriNaruto Do you have discord where we can chat or something or only here

**Comment by modz4567** [comment]
@MouriNaruto this a good suggestion from what can understand it will still load context menu on both Windows 11 and below

**Comment by modz2014** [comment]
@MouriNaruto i shared a Wix Installer for NanaZip Example for some people if they want to try

**Comment by modz2014** [comment]
@MouriNaruto I updated the IsWindows11OrLater() function approach to be a better one so hopefully this one will work better for you If you need any more information please let me know Also I have a Wix Installer Example did you want me to send this to you as well

**Comment by modz2014** [comment]
@MouriNaruto can we add the those hash commands under a submenu so it looks nicer when right-clicking

**Comment by MouriNaruto** [comment]
> @MouriNaruto can we add the those hash commands under a submenu so it looks nicer when right-clicking

Due to the limitation of IExplorerCommand based context menu, we only have 16 items as maximum.

So, I think I will try to continue to reduce items.

Kenji Mouri

**Comment by modz2014** [comment]
@MouriNaruto can you open the discussion tab here on GitHub to ask questions I want to know what else needs to be done before the new release

**Comment by MouriNaruto** [comment]
> @MouriNaruto can you open the discussion tab here on GitHub to ask questions I want to know what else needs to be done before the new release

I don't use GitHub discussion feature because it makes it messier.

There are many things I need to do before I release the next preview:

- Split the LZMA SDK as a separate module in NanaZip.
- Synchronize the LZMA SDK and 7-Zip implementations to 23.01 in NanaZip.
- Three features originally in 2.0 release but I delayed that.
- More XAML UI powered by Mile.Xaml.
- JSON-based configuration.
- Migration for some generators for project development.

Kenji Mouri

**Comment by modz2014** [comment]
Is there anywhere we can discuss somewhere besides opening a issue or what
not

**Comment by modz2014** [comment]
Could you please provide information on which older version or build NanaZip is based upon or derived from?

**Comment by MouriNaruto** [comment]
> Could you please provide information on which older version or build NanaZip is based upon or derived from?

NanaZip is based on 7-Zip 21.03 with heavily modifications for project building process originally.

Kenji Mouri

**Comment by modz2014** [comment]
Do you have any specific preferences for features or changes from the latest build? @MouriNaruto

**Comment by MouriNaruto** [comment]
> Do you have any specific preferences for features or changes from the latest build? @MouriNaruto

I'm trying to synchronize the LZMA SDK and 7-Zip implementations to 23.01 in NanaZip first. And I hope I can finish that this week.

Kenji Mouri

**Comment by modz2014** [comment]
i have Updated for Open folder destination after extraction is complete mention here https://github.com/M2Team/NanaZip/issues/272#issuecomment-1719931016

**Comment by modz2014** [comment]
I've noticed that when we right-click on a file (@MouriNaruto), the context menu displays certain options twice. Upon closer inspection, I'm wondering about the necessity of having both 'Compress to' and 'Email' options. While 'Compress to' successfully opens the program, 'Email' does not trigger any action. Wouldn't it be more user-friendly to streamline this and simply have 'Compress' and 'Email' as options in the context menu? This way, users can choose their preferred actions more seamlessly
Screenshot 2023-09-29 142452
Screenshot 2023-09-29 142641

**Comment by modz4567** [comment]
I see you have added a few more things in NanaZip I'm hoping @MouriNaruto accepts the pull request @modz2014 would be greate to have that option to open destination of extracted  files ect and I love how you removed the duplicated context menu for windows 11

**Comment by MouriNaruto** [comment]
I won't accept the suggestion and the PR of hiding NanaZip item in the legacy context menu because there is no proper way to implement.

Due to packaged shell extensions running out of process, we cannot check the progress is File Explorer or third-party applications which need shell extensions.

Due to many people may like to select all files in the folder which the file count is large like the System32 folder, it's not suitable for using okToBeSlow to optimize.

I think I will change "Compress and email" to "Compress and share" as the result with offline talking with @AndromedaMelody for https://github.com/M2Team/NanaZip/pull/322. (AndromedaMelody also suggests me to close his PR because he think the feature is right but the implement way is wrong.)

Kenji Mouri

**Comment by modz2014** [comment]
@MouriNaruto  i have just wondering thats all did you take a look at the other code that i added from this suggestion https://github.com/M2Team/NanaZip/issues/272#issuecomment-1719931016

**Comment by MouriNaruto** [comment]
> @MouriNaruto i have just wondering thats all did you take a look at the other code that i added from this suggestion [#272 (comment)](https://github.com/M2Team/NanaZip/issues/272#issuecomment-1719931016)

I have read it and found it may not be integrated into NanaZip's source code properly. I need to modify it first.

P.S. I will rewrite the content menu implementation in the recent days.

Kenji Mouri

**Comment by modz2014** [comment]
@MouriNaruto is already integrated

**Comment by MouriNaruto** [comment]
> @MouriNaruto is it already integrated also what are your thoughts about creating iso images i have started it last night

It's not the current development goal for me because I'm trying to modernize the UI at the current stage.

Kenji Mouri

**Comment by modz2014** [comment]
ok i have almost finished it just added a few more touches to it then I might send it to you or update to this pull request should I close this I guess or

**Comment by modz2014** [comment]
ok i have almost finished it just added a few more touches to it then I might send it to you or update to this pull request should I close this I guess or  @MouriNaruto

**Pull request closed without merging**
