### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by ChuckMichael**
Added missing strings

### CODE REVIEW

**Comment by MouriNaruto** [comment]
Thanks. I have merged.

Kenji Mouri

**Comment by Dziubek** [comment]
Hi, the translation of several items in the SETTINGS menu is still missing
image

**Comment by ChuckMichael** [comment]
Hi @Dziubek,
I found out, how to translate these items. See #407.

**Comment by Dziubek** [comment]
Hi,
I don't know if you have also contributed to this thread.
If not then maybe you will also verify (update) the translation in the official [7-zip release](https://sourceforge.net/p/sevenzip/discussion/45797/thread/120e904fdf/?page=4)

**Comment by ChuckMichael** [comment]
> Hi, I don't know if you have also contributed to this thread. If not then maybe you will also verify (update) the translation in the official [7-zip release](https://sourceforge.net/p/sevenzip/discussion/45797/thread/120e904fdf/?page=4)
> 
> [7-Zip 24.xx translation for new strings](https://sourceforge.net/p/sevenzip/discussion/45797/thread/0f9d8add1e/)

Polish translation is finished in 100% for 7-Zip 24.04 _(and 24.05 as of there's nothing new to translate)_.

**Pull request merged**
